[package]
name = "util"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/microsoft/electionguard-rust"
license = "Apache-2.0 OR MIT"
publish = false

[features] #=============================================================================== features

default = [
    "eg-forbid-unsafe-code",
]

eg-allow-unsafe-code                    = [ ]
eg-forbid-unsafe-code                   = [ ]

[dependencies] #======================================================================= dependencies

#--------------- Defined in this workspace

#--------------- From crates.io

anyhow.workspace = true
either.workspace = true
faster-hex.workspace = true
getrandom.workspace = true
itertools.workspace = true
nutype.workspace = true
static_assertions.workspace = true
thiserror.workspace = true

#--------------- Num-*, typenum, generic-array, hybrid-array

# generic-array.workspace = true
# hybrid-array.workspace = true
num-bigint.workspace = true
num-integer.workspace = true
num-traits.workspace = true
typenum.workspace = true

#--------------- Rand

rand.workspace = true
rand_core.workspace = true
rand_distr.workspace = true
rand_xorshift.workspace = true

#--------------- RustCrypto

# crypto-common.workspace = true
# crypto-bigint.workspace = true
# digest.workspace = true
# hmac.workspace = true
# sha2.workspace = true
sha3.workspace = true
zeroize.workspace = true

#--------------- Serde

serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true

#--------------- Tracing

tracing.workspace = true
#valuable.workspace = true

[dev-dependencies] #=============================================================== dev-dependencies

insta = { version = "1.43.1", features = ["ron"] }
