[workspace]
resolver = "2"

members = [
  "demo-eg",
  "eg",
  "eg-resourceproducer-filesystem",
  "formulator",
  # "electionguard",
  # "preencrypted",
  "util",
]

[workspace.dependencies]

#--- Defined in this workspace
eg = { path = "./eg" }
eg-resourceproducer-filesystem = { path = "./eg-resourceproducer-filesystem" }
# electionguard = { path = "./electionguard" }
# preencrypted = { path = "./preencrypted" }
util = { path = "./util" }

#--- From crates.io

arbitrary = { version = "1.4.1", features = ["derive"] }
derive_arbitrary  = "1.4.1"

anyhow = "1.0.95"
bimap = "0.6.3"
bitflags = { version = "2.8.0", features = ["std"] }
clap = { version = "4.5.17", features = ["derive", "env"] }
cfg-if = "1.0.0"
downcast-rs = "2.0.1"
derive_more = { version = "1.0.0", default-features = false }
either = { version = "1.13.0", features = ["serde"] }
erased-serde = { version = "0.4.5" }
faster-hex = { version = "0.10.0" }
getrandom = { version = "0.3.1", default-features = false }
#generic-array = { version = "1.2.0", default-features = false, features = ["const-default", "faster-hex", "serde", "typenum", "zeroize"] }
hashbrown = { version = "0.15.2", default-features = false, features = [
    #"allocator-api2",
    #"equivalent",
    "inline-more",
    #"rayon",
    "raw-entry",
    "serde"
] } # 
indoc = "2.0.5"
inventory = "0.3.17"
itertools = "0.14.0"
lazy_static = "1.4"
maybe-owned = "0.3.4"
num-bigint = { version = "0.4.6", features = ["serde"] }
num-integer = "0.1.46"
num-traits = { version = "0.2.19", features = ["libm"] }
nutype = { version = "0.6.0", default-features = false, features = ["new_unchecked", "serde", "std"] }

pathfinding = "4.13.1"  # defines no features
# num-traits = "0.2.19"              # pathfinding
# indexmap = "2.5.0"                 # pathfinding
# rustc-hash = "2.0.0"               # pathfinding
# integer-sqrt = "0.1.5"             # pathfinding
# deprecate-until = "0.1.1"          # pathfinding

proptest = "1.6.0"
proptest-arbitrary-interop = "0.1.0"
rand = { version = "0.9.0", default-features = false, features = [
    "alloc",
] }
rand_core     = { version = "0.9.0", default-features = false, features = ["std"] }
# rand_distr  = { version = "0.9.0", default-features = false, features = ["alloc", "std_math"] }
rand_xorshift = "0.3.0"
rustc-stable-hash = "0.1.1"

#3 TODO ? rand_distr = { version = "0.6.4", default-features = false, features = ["alloc", "std_math"] }
serde = { version = "1.0.217", features = ["derive", "rc", "std"] }
serde_json = { version = "1.0.135", features = ["preserve_order", "std"] }

smallbitvec = "2.5.3"
static_assertions = "1.1.0"
strum = { version = "0.26.3", features = ["derive", "std"] }
strum_macros = "0.26.4"
thiserror = "2.0.0"                # pathfinding

#--- Tracing

tracing = { version = "0.1.41", default-features = false, features = ["std", "attributes"] }
# tracing: "pin-project-lite 0.2.15"
# tracing: "tracing-core 0.1.33"
# tracing-core: "once_cell 1.20.2"

tracing-subscriber = { version = "0.3.19", default-features = false, features = ["fmt", "smallvec", "std"] }
# tracing-subscriber: "tracing-core 0.1.33"
# tracing-subscriber "fmt": "sharded-slab 0.1.7"
# tracing-subscriber "fmt": "thread_local 1.1.8"
# tracing-subscriber "smallvec": "smallvec 1.13.2"

#valuable = { version = "0.1.0", features = ["derive", "std"] }
# tracing-core "valuable": "valuable" version = "0.1.0"

# tracing-subscriber "parking_lot": "parking_lot 0.12.3"
# tracing-subscriber "parking_lot": "parking_lot_core 0.9.10"
# tracing-subscriber "parking_lot": "smallvec 1.13.2"
# tracing-subscriber "parking_lot": "redox_syscall 0.5.7"
# tracing-subscriber "parking_lot": "scopeguard 1.2.0"
# tracing-subscriber "parking_lot": "lock_api 0.4.12"

#with default features: newly dragged in by tracing and/or -subscriber "tracing-attributes 0.1.28"
#with default features: newly dragged in by tracing and/or -subscriber "tracing-log 0.2.0"
#with default features: newly dragged in by tracing and/or -subscriber "overload 0.1.1"
#with default features: newly dragged in by tracing and/or -subscriber "nu-ansi-term 0.46.0"
#with default features: newly dragged in by tracing and/or -subscriber "log 0.4.22"
#with default features: newly dragged in by tracing and/or -subscriber "winapi 0.3.9"
#with default features: newly dragged in by tracing and/or -subscriber "winapi-i686-pc-windows-gnu 0.4.0"
#with default features: newly dragged in by tracing and/or -subscriber "winapi-x86_64-pc-windows-gnu 0.4.0"

#--- RustCrypto

# https://crates.io/crates/block-buffer/0.10.4
# https://github.com/RustCrypto/utils/blob/block-buffer-v0.10.4/block-buffer/Cargo.toml
block-buffer = { version = "0.10.4", default-features = false, features = [] }

# https://crates.io/crates/crypto-common/0.1.6
# https://github.com/RustCrypto/traits/blob/crypto-common-v0.1.6/crypto-common/Cargo.toml
# https://github.com/RustCrypto/traits/blob/25614e2d5a4ccbb0cfde23367a93c8bcdbfe421a/crypto-common/Cargo.toml
crypto-common = { version = "0.1.6", default-features = false, features = ["getrandom", "rand_core", "std"] }

# Next release 0.11 probably not before Rust 1.85 2024 edition Feb/March 2025 https://github.com/RustCrypto/traits/issues/1571
digest = { version = "0.10.7", default-features = false, features = [
    "block-buffer",
    # "const-oid",
    "core-api",
    "mac",
    # "oid",
    "rand_core",
    # "subtle",
    "std", "alloc",
    # "dev", "blobby",
    # depends on digest 0.11 "zeroize",
] }

# https://crates.io/crates/hmac/0.12.1
# https://github.com/RustCrypto/MACs/blob/hmac-v0.12.1/hmac/Cargo.toml
# https://github.com/RustCrypto/MACs/blob/46797e3b44973a30edb9d7f3a3ebb41810061d90/hmac/Cargo.toml
hmac = { version = "0.12.1", default-features = false, features = ["std", "reset"] }

# https://crates.io/crates/sha2/0.10.8
# https://github.com/RustCrypto/hashes/blob/sha2-v0.10.8/sha2/Cargo.toml
# https://github.com/RustCrypto/hashes/blob/c6decdf36f64e4c651edcf60e12527acfb9d9c9c/sha2/Cargo.toml
# Next release depends on digest 0.11 https://github.com/RustCrypto/hashes/issues/584
sha2 = { version = "0.10.8", default-features = false, features = [
    "compress",
    # "oid",
    "std",
    # depends on digest 0.11 "zeroize",
] }

# https://crates.io/crates/sha3/0.10.8
# https://github.com/RustCrypto/hashes/blob/sha3/v0.10.8/sha3/Cargo.toml
# https://github.com/RustCrypto/hashes/blob/62d84e1da613ab4f5a3259326e81ef25c6c012e1/sha3/Cargo.toml
# Next release depends on digest 0.11 https://github.com/RustCrypto/hashes/issues/584
sha3 = { version = "0.10.8", default-features = false, features = [
    "reset",
    "std",
    # depends on digest 0.11 "zeroize",
] }

# https://github.com/RustCrypto/utils/blob/zeroize-v1.8.1/zeroize/Cargo.toml
zeroize = { version = "1.8.1", default-features = false, features = [
    "derive", "zeroize_derive",
    "serde",
    "std", "alloc",
    "simd",
] }
